server:
  port: 8080

spring:
  redis:
    type: single # cluster
    host: 127.0.0.1
    port: 6379
    password:
#    cluster:
#      nodes:
#        - 127.0.0.1:7031
#        - 127.0.0.1:7032
#        - 127.0.0.1:7033
#        - 127.0.0.1:7034
#        - 127.0.0.1:7035
#        - 127.0.0.1:7036
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
